version: '3.9'

services:
  NenekaBot:
    container_name: NenekaBot
    image: nenekabot
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - "${APP_PORT}"
    volumes:
      - app_data:/var/app/data
    env_file: .env
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:/var/lib/redis/data/

volumes:
  app_data:
  postgres_data:
  redis_data:
  