version: '3.9'

services:
  nenekabot:
    container_name: NenekaBot
    image: nenekabot
    restart: unless-stopped
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - "${APP_PORTS}"
    networks:
      - neneka-bot-network
    env_file: .env
    entrypoint: ["python", "main.py"]
    depends_on:
      - postgres
    volumes:
      - ./data:/data
      - .:/app
    
  postgres:
    container_name: nenekabot_postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORTS}"
    networks:
      - neneka-bot-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  neneka-bot-network:
    driver: bridge