version: '3.9'

services:
  nenekabot:
    container_name: NenekaBot
    image: nenekabot
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - "${APP_PORT}"
    networks:
      - neneka-bot-network
    env_file: .env
    entrypoint: ["python", "main.py"]
    depends_on:
      - postgres
      - redis
    
  postgres:
    container_name: nenekabot_postgres
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}"
    networks:
      - neneka-bot-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    container_name: nenekabot_redis
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:/var/lib/redis/data/
    networks:
      - neneka-bot-network

volumes:
  postgres_data:
  redis_data:

networks:
  neneka-bot-network:
    driver: bridge